import type { Metadata } from "next";
import { Cinzel, Exo, Michroma } from "next/font/google";

const cinzel = Cinzel({ variable: "--font-cinzel", subsets: ["latin"], display: "swap" });
const exo = Exo({ variable: "--font-exo", subsets: ["latin"], display: "swap" });
const michroma = Michroma({ variable: "--font-michroma", subsets: ["latin"], weight: "400", display: "swap" });

export const metadata: Metadata = {
  title: "Project Kronos",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased ${cinzel.variable} ${exo.variable} ${michroma.variable}`}>
        {children}
      </body>
    </html>
  );
}
